### ISSUE TITLE
shift function documentation

### ISSUE THREAD

**Issue by flip111** [rowtype-yoga/purescript-js-bigints#11]
Would it be ok to add a comment in the documentation which argument of the shift functions is the number and which is the amount of bits to shift? The original docs of the underlying javascript function describe it a bit clearer https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Left_shift

**Comment by sigma-andex** [comment]
Sure! Wanna create a PR?

**Comment by sigma-andex** [comment]
Done #13 , thx @flip111
