### ISSUE TITLE
Simplify the module's name

### ISSUE THREAD

**Issue by gbagan** [rowtype-yoga/purescript-js-bigints#4]
I find Js.BigInt.BigInt to be a bit long and redundant.
Why not just Js.BigInt?

**Comment by sigma-andex** [comment]
Sure, go ahead!

**Comment by sigma-andex** [comment]
@gbagan want to create a new release for it and update the registry?

**Comment by gbagan** [comment]
Yes, I think it is a good idea.
Maybe just add a link to Pursuit on the github page before that.

**Comment by gbagan** [comment]
I took the liberty of directly editing the readme.
