### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by gbagan** [rowtype-yoga/purescript-js-bigints#8]
Hi,

could you release a new version with `toInt` and `toNumber` (maybe 2.1.0 since there is no breaking change)?
I need this for `purescript-rationals`.

Thanks

**Comment by sigma-andex** [comment]
@gbagan working on it https://github.com/purescript/registry/issues/254

**Comment by sigma-andex** [comment]
Done: https://github.com/purescript/registry/issues/256
